# Install agents from this repo to %USERPROFILE%\.claude\agents\
# Usage: .\scripts\install\install_agents.ps1 [-IndexOnly]
#
# -IndexOnly rebuilds the repository's agents/INDEX.md and writes nothing
# else -- not to ~/.claude, not to any target. It is the switch safe for an
# agent: AGENTS.md says an agent does not install, so this is the only mode
# an agent may run unattended. Without it, this script performs a real
# install into the operator's ~/.claude/agents and must not be run by an
# agent (DG-423, the same incident that added -IndexOnly to
# install_skills.ps1).
#
# Requirements: PowerShell 5.1+ or PowerShell Core 7+ (Windows / macOS / Linux)

param(
    [switch]$IndexOnly
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir       = $PSScriptRoot
$LocalAgentsDir  = Resolve-Path (Join-Path $ScriptDir "..\..\agents")
$GlobalAgentsDir = Join-Path $HOME ".claude\agents"
$LocalIndex      = Join-Path $LocalAgentsDir "INDEX.md"

Write-Host "=================================================" -ForegroundColor Blue
Write-Host "   Claude Agents Synchronizer                   " -ForegroundColor Blue
Write-Host "=================================================" -ForegroundColor Blue

if (-not (Test-Path $LocalAgentsDir)) {
    Write-Host "Error: agents directory not found at $LocalAgentsDir" -ForegroundColor Red
    exit 1
}

# Everything below this point that writes or creates anything outside the
# repository is gated on $IndexOnly being false. $GlobalAgentsDir is the
# target's root and the first thing a real install creates -- -IndexOnly
# never reaches that call.
if ($IndexOnly) {
    Write-Host "  -IndexOnly: rebuilding agents/INDEX.md, installing nothing" -ForegroundColor Yellow
} else {
    New-Item -ItemType Directory -Force -Path $GlobalAgentsDir | Out-Null
}

Write-Host ""
Write-Host "Source: $LocalAgentsDir"
Write-Host "Target: $GlobalAgentsDir"
Write-Host ""

$NewCount     = 0
$UpdatedCount = 0

# Collect all .md agent files (top-level only), sorted for deterministic output.
# INDEX.md is generated below, not an agent -- it lives in agents/ so the repo
# carries the same index the install does, which means it has to be excluded
# here or the next run would install the index as an extra agent.
$AgentFiles = Get-ChildItem -Path $LocalAgentsDir -Filter "*.md" -File |
              Where-Object { $_.Name -ne "INDEX.md" } |
              Sort-Object Name

# AGENTS.md routes all agent discovery through INDEX.md, so a run that installs
# agents without refreshing it leaves a live dangling reference.
$IndexLines = New-Object System.Collections.Generic.List[string]
$IndexLines.Add("# Agent Index")
$IndexLines.Add("")
$IndexLines.Add("Map a task to the agent that owns it. Read this before delegating $([char]0x2014) do NOT guess agent")
$IndexLines.Add("names or paths from memory.")
$IndexLines.Add("")
$IndexLines.Add("Generated by ``scripts/install/install_agents`` (.sh and .ps1 write identical bytes). Do not")
$IndexLines.Add("edit by hand; edit the agent frontmatter instead.")
$IndexLines.Add("")

foreach ($AgentFile in $AgentFiles) {
    $AgentName  = [System.IO.Path]::GetFileNameWithoutExtension($AgentFile.Name)

    # -IndexOnly never creates, reads or writes anything under
    # $GlobalAgentsDir. That decision only matters for the install messages,
    # which -IndexOnly does not print.
    if (-not $IndexOnly) {
        $TargetFile = Join-Path $GlobalAgentsDir "$AgentName.md"
        $IsNew      = -not (Test-Path $TargetFile)

        $ShouldCopy = $true
        if (Test-Path $TargetFile) {
            $SrcHash  = (Get-FileHash $AgentFile.FullName -Algorithm MD5).Hash
            $DestHash = (Get-FileHash $TargetFile         -Algorithm MD5).Hash
            $ShouldCopy = ($SrcHash -ne $DestHash)
        }

        if ($ShouldCopy) {
            Copy-Item -Path $AgentFile.FullName -Destination $TargetFile -Force
        }

        if ($IsNew) {
            Write-Host "  [+] Installed: $AgentName" -ForegroundColor Green
            $NewCount++
        } else {
            Write-Host "  [*] Updated:   $AgentName"
            $UpdatedCount++
        }
    }

    # Checked against DG-378 and clean: unlike install_skills.ps1, this reads
    # the same frontmatter keys install_agents.sh reads -- `^description: ` and
    # `^model: ` -- so it never depended on the pre-frontmatter `**Description:**`
    # body line and never published a blank row. Verified by running it, not by
    # reading it: a sandboxed run on Windows produced all three agents with full
    # descriptions and correct models.
    #
    # That run also surfaced a drift from install_agents.sh -- a BOM, CRLF, a
    # trailing blank line, `-` for the em-dash, a Substring cut that kept the
    # space the shell strips, and its own filename in the header -- so a Windows
    # run and a macOS run rewrote each other's committed agents/INDEX.md. Fixed
    # in DG-380: the em-dash is written as [char]0x2014 so this file stays ASCII
    # for Windows PowerShell 5.1, and the write path is DG-378's.
    #
    # Both may legitimately be absent; Select-Object -First 1 on an empty match
    # yields $null rather than throwing, which is what we want here.
    $Content = Get-Content -LiteralPath $AgentFile.FullName -Encoding UTF8
    $Desc  = ($Content | Where-Object { $_ -match '^description: ' } | Select-Object -First 1)
    $Model = ($Content | Where-Object { $_ -match '^model: ' }       | Select-Object -First 1)
    if ($Desc)  { $Desc  = $Desc  -replace '^description: ', '' } else { $Desc  = "" }
    if ($Model) { $Model = $Model -replace '^model: ', ''       } else { $Model = "" }
    # Same cut as _truncate.py: the first 200 characters, trailing space dropped.
    $Desc = $Desc.Substring(0, [Math]::Min(200, $Desc.Length)).TrimEnd()

    $IndexLines.Add("- ``$AgentName`` (``$Model``) $([char]0x2014) $Desc")
    $IndexLines.Add("  Path: `$HOME/.claude/agents/$AgentName.md")
    $IndexLines.Add("")
}

# The DG-378 write path, for the same reason: this index is committed, so it
# must be the bytes install_agents.sh writes and a commit accepts -- no BOM, LF,
# and no trailing blank line for end-of-file-fixer to strip.
$IndexText = ($IndexLines -join "`n").TrimEnd("`n") + "`n"
$Utf8NoBom = New-Object System.Text.UTF8Encoding $false

# -IndexOnly writes only the repository's own agents/INDEX.md and returns
# here -- before $GlobalAgentsDir\INDEX.md is ever touched.
if ($IndexOnly) {
    $TempIndex = [System.IO.Path]::GetTempFileName()
    [System.IO.File]::WriteAllText($TempIndex, $IndexText, $Utf8NoBom)
    Move-Item -Path $TempIndex -Destination $LocalIndex -Force

    Write-Host ""
    Write-Host "Done." -ForegroundColor Green -NoNewline
    Write-Host " Rebuilt $LocalIndex. Nothing was installed."
    exit 0
}

$IndexFile = Join-Path $GlobalAgentsDir "INDEX.md"
$TempIndex = [System.IO.Path]::GetTempFileName()
[System.IO.File]::WriteAllText($TempIndex, $IndexText, $Utf8NoBom)
Move-Item -Path $TempIndex -Destination $IndexFile -Force
Copy-Item -Path $IndexFile -Destination $LocalIndex -Force

Write-Host ""
Write-Host "Sync complete." -ForegroundColor Green
Write-Host "  $NewCount new  |  $UpdatedCount updated"
Write-Host "  Agents installed to: $GlobalAgentsDir"
Write-Host "  INDEX.md: $IndexFile"

# Anything installed that this repo does not produce. Reported, never deleted.
$Installed = Get-ChildItem -Path $GlobalAgentsDir -Filter "*.md" -File |
             Where-Object { $_.Name -ne "INDEX.md" } |
             ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
$Ours = $AgentFiles | ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
$Orphans = $Installed | Where-Object { $Ours -notcontains $_ }
if ($Orphans) {
    Write-Host ""
    Write-Host "Installed but not produced here:" -ForegroundColor Yellow
    foreach ($Orphan in $Orphans) { Write-Host "  ~/.claude/agents/$Orphan.md" }
    Write-Host "  Left in place. Add the source to agents/, or remove them yourself."
}
