# Install agents from this repo to %USERPROFILE%\.claude\agents\
# Usage: .\scripts\install\install_agents.ps1
#
# KNOWN GAP -- this does less than install_agents.sh, and the difference is
# stated rather than hidden. The shell version also accepts --index-only
# to rebuild agents/INDEX.md without installing anything. That is not
# implemented here.
#
# Not an oversight: this project has no Windows machine to run PowerShell
# against, and an untested installer that writes into a shared config
# directory is worse than one that does less and says so.
#
# Requirements: PowerShell 5.1+ or PowerShell Core 7+ (Windows / macOS / Linux)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$ScriptDir       = $PSScriptRoot
$LocalAgentsDir  = Resolve-Path (Join-Path $ScriptDir "..\..\agents")
$GlobalAgentsDir = Join-Path $HOME ".claude\agents"

Write-Host "=================================================" -ForegroundColor Blue
Write-Host "   Claude Agents Synchronizer                   " -ForegroundColor Blue
Write-Host "=================================================" -ForegroundColor Blue

if (-not (Test-Path $LocalAgentsDir)) {
    Write-Host "Error: agents directory not found at $LocalAgentsDir" -ForegroundColor Red
    exit 1
}

New-Item -ItemType Directory -Force -Path $GlobalAgentsDir | Out-Null

Write-Host ""
Write-Host "Source: $LocalAgentsDir"
Write-Host "Target: $GlobalAgentsDir"
Write-Host ""

$NewCount     = 0
$UpdatedCount = 0

# Collect all .md agent files (top-level only), sorted for deterministic output.
# INDEX.md is generated below, not an agent -- it lives in agents/ so the repo
# carries the same index the install does, which means it has to be excluded
# here or the next run would install the index as an extra agent.
$AgentFiles = Get-ChildItem -Path $LocalAgentsDir -Filter "*.md" -File |
              Where-Object { $_.Name -ne "INDEX.md" } |
              Sort-Object Name

# CLAUDE.md routes all agent discovery through INDEX.md, so a run that installs
# agents without refreshing it leaves a live dangling reference.
$IndexLines = New-Object System.Collections.Generic.List[string]
$IndexLines.Add("# Agent Index")
$IndexLines.Add("")
$IndexLines.Add("Map a task to the agent that owns it. Read this before delegating - do NOT guess agent")
$IndexLines.Add("names or paths from memory.")
$IndexLines.Add("")
$IndexLines.Add("Generated by ``scripts/install/install_agents.ps1``. Do not edit by hand; edit the agent")
$IndexLines.Add("frontmatter instead.")
$IndexLines.Add("")

foreach ($AgentFile in $AgentFiles) {
    $AgentName  = [System.IO.Path]::GetFileNameWithoutExtension($AgentFile.Name)
    $TargetFile = Join-Path $GlobalAgentsDir "$AgentName.md"
    $IsNew      = -not (Test-Path $TargetFile)

    $ShouldCopy = $true
    if (Test-Path $TargetFile) {
        $SrcHash  = (Get-FileHash $AgentFile.FullName -Algorithm MD5).Hash
        $DestHash = (Get-FileHash $TargetFile         -Algorithm MD5).Hash
        $ShouldCopy = ($SrcHash -ne $DestHash)
    }

    if ($ShouldCopy) {
        Copy-Item -Path $AgentFile.FullName -Destination $TargetFile -Force
    }

    if ($IsNew) {
        Write-Host "  [+] Installed: $AgentName" -ForegroundColor Green
        $NewCount++
    } else {
        Write-Host "  [*] Updated:   $AgentName"
        $UpdatedCount++
    }

    # Both may legitimately be absent; Select-Object -First 1 on an empty match
    # yields $null rather than throwing, which is what we want here.
    $Content = Get-Content $AgentFile.FullName
    $Desc  = ($Content | Where-Object { $_ -match '^description: ' } | Select-Object -First 1)
    $Model = ($Content | Where-Object { $_ -match '^model: ' }       | Select-Object -First 1)
    if ($Desc)  { $Desc  = $Desc  -replace '^description: ', '' } else { $Desc  = "" }
    if ($Model) { $Model = $Model -replace '^model: ', ''       } else { $Model = "" }
    if ($Desc.Length -gt 200) { $Desc = $Desc.Substring(0, 200) }

    $IndexLines.Add("- ``$AgentName`` (``$Model``) - $Desc")
    $IndexLines.Add("  Path: `$HOME/.claude/agents/$AgentName.md")
    $IndexLines.Add("")
}

$IndexFile = Join-Path $GlobalAgentsDir "INDEX.md"
Set-Content -Path $IndexFile -Value $IndexLines -Encoding UTF8
Copy-Item -Path $IndexFile -Destination (Join-Path $LocalAgentsDir "INDEX.md") -Force

Write-Host ""
Write-Host "Sync complete." -ForegroundColor Green
Write-Host "  $NewCount new  |  $UpdatedCount updated"
Write-Host "  Agents installed to: $GlobalAgentsDir"
Write-Host "  INDEX.md: $IndexFile"

# Anything installed that this repo does not produce. Reported, never deleted.
$Installed = Get-ChildItem -Path $GlobalAgentsDir -Filter "*.md" -File |
             Where-Object { $_.Name -ne "INDEX.md" } |
             ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
$Ours = $AgentFiles | ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }
$Orphans = $Installed | Where-Object { $Ours -notcontains $_ }
if ($Orphans) {
    Write-Host ""
    Write-Host "Installed but not produced here:" -ForegroundColor Yellow
    foreach ($Orphan in $Orphans) { Write-Host "  ~/.claude/agents/$Orphan.md" }
    Write-Host "  Left in place. Add the source to agents/, or remove them yourself."
}
