#!/bin/bash
# Deploy agents from this repo to ~/.claude/agents/
# Works from any directory and any clone location.
# Usage: bash scripts/install/sync_agents.sh

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOCAL_AGENTS_DIR="$PROJECT_ROOT/agents"
GLOBAL_AGENTS_DIR="$HOME/.claude/agents"

echo -e "${BLUE}=================================================${NC}"
echo -e "${BLUE}   Claude Agents Installer                      ${NC}"
echo -e "${BLUE}=================================================${NC}"
echo -e "  Project:  $PROJECT_ROOT"
echo -e "  Source:   $LOCAL_AGENTS_DIR"
echo -e "  Target:   $GLOBAL_AGENTS_DIR"
echo ""

if [ ! -d "$LOCAL_AGENTS_DIR" ]; then
  echo -e "${RED}Error: agents/ directory not found at $LOCAL_AGENTS_DIR${NC}"
  echo -e "${RED}Make sure you are running this from inside the drunken-ai-team repo.${NC}"
  exit 1
fi

mkdir -p "$GLOBAL_AGENTS_DIR"

# Prefer rsync; fall back to cp if not available.
if command -v rsync >/dev/null 2>&1; then
  _copy_file() { rsync -a --checksum "$1" "$2" 2>/dev/null; }
else
  echo -e "${YELLOW}  rsync not found — using cp (all files will be copied)${NC}"
  _copy_file() { cp "$1" "$2"; }
fi

NEW_COUNT=0
UPDATED_COUNT=0

# INDEX.md is generated below, not an agent. It lives in agents/ so the repo
# carries the same index the install does, which means the discovery glob has
# to exclude it or the next run would install the index as a 14th agent.
_agent_list=$(mktemp)
find "$LOCAL_AGENTS_DIR" -maxdepth 1 -type f -name "*.md" '!' -name "INDEX.md" \
  | sort > "$_agent_list"

# Build INDEX.md in a temp file and replace atomically at the end. CLAUDE.md
# routes all agent discovery through this file, so a run that installs agents
# without refreshing it leaves a live dangling reference.
TEMP_INDEX=$(mktemp)
cat > "$TEMP_INDEX" << 'HEADER'
# Agent Index

Map a task to the agent that owns it. Read this before delegating — do NOT guess agent
names or paths from memory.

Generated by `scripts/install/sync_agents.sh`. Do not edit by hand; edit the agent
frontmatter instead.

HEADER

while IFS= read -r agent_file; do
  agent_name="$(basename "$agent_file" .md)"
  TARGET_FILE="$GLOBAL_AGENTS_DIR/$agent_name.md"

  IS_NEW=false
  [ ! -f "$TARGET_FILE" ] && IS_NEW=true

  _copy_file "$agent_file" "$TARGET_FILE"

  if [ "$IS_NEW" = true ]; then
    echo -e "${GREEN}  [+] Installed:${NC} $agent_name"
    NEW_COUNT=$((NEW_COUNT + 1))
  else
    echo -e "  [*] Updated:   $agent_name"
    UPDATED_COUNT=$((UPDATED_COUNT + 1))
  fi

  # Every extraction here is a grep that can legitimately find nothing, and
  # under `set -euo pipefail` an unmatched grep would kill the whole run --
  # exactly the failure that left 29 of 30 skills stale for two months. Hence
  # `|| true` on each, deliberately.
  DESC=$(grep -m1 "^description: " "$agent_file" 2>/dev/null \
    | sed 's/^description: //' | cut -c1-200 || true)
  MODEL=$(grep -m1 "^model: " "$agent_file" 2>/dev/null | sed 's/^model: //' || true)

  echo "- \`${agent_name}\` (\`${MODEL}\`) — ${DESC}" >> "$TEMP_INDEX"
  echo "  Path: \$HOME/.claude/agents/${agent_name}.md" >> "$TEMP_INDEX"
  echo "" >> "$TEMP_INDEX"

done < "$_agent_list"
rm -f "$_agent_list"

INDEX_FILE="$GLOBAL_AGENTS_DIR/INDEX.md"
mv "$TEMP_INDEX" "$INDEX_FILE"
cp "$INDEX_FILE" "$LOCAL_AGENTS_DIR/INDEX.md"

echo ""
echo -e "${GREEN}Done.${NC} $NEW_COUNT new  |  $UPDATED_COUNT updated"
echo -e "  Agents:   $GLOBAL_AGENTS_DIR"
echo -e "  INDEX.md: $INDEX_FILE"

# Anything installed that this repo does not produce. Reported, never deleted:
# removing is the operator's call, and a stale agent still being offered to
# every session is worth knowing about either way.
_installed=$(find "$GLOBAL_AGENTS_DIR" -maxdepth 1 -type f -name "*.md" \
  '!' -name "INDEX.md" -exec basename {} .md ';' | sort -u)
_ours=$(find "$LOCAL_AGENTS_DIR" -maxdepth 1 -type f -name "*.md" \
  '!' -name "INDEX.md" -exec basename {} .md ';' | sort -u)
_orphans=$(comm -23 <(echo "$_installed") <(echo "$_ours"))
if [ -n "$_orphans" ]; then
  echo ""
  echo -e "${YELLOW}Installed but not produced here:${NC}"
  echo "$_orphans" | sed 's|^|  ~/.claude/agents/|;s|$|.md|'
  echo -e "  Left in place. Add the source to agents/, or remove them yourself."
fi
