# mypy: ignore-errors
"""DG-271. The compiled dev lockfile has to agree with what compiled it.

Two ways it had drifted:

`pyproject.toml` pins `ruff==0.16.4` exactly, and it explains at length why the
formatter cannot take a range — 0.15.22 and 0.16.4 disagree about blank lines
before a class, which turned `develop` red and dragged two unrelated PRs down
with it (DG-270). `requirements-dev.txt` still pinned 0.15.20: the exact
version DG-270 was written to stop anyone resolving.

`scripts/lock_deps.sh` regenerates it with `pip-compile`, while the file's own
header records `uv pip compile`. Two generators for one artefact is the shape
DG-280 had, and it ends the same way — whoever regenerates decides what lands.

`pip-audit --strict` reads this file in CI, so a stale pin is not cosmetic: the
audit is answering about versions nobody installs.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = REPO_ROOT / "pyproject.toml"
REQUIREMENTS_DEV = REPO_ROOT / "requirements-dev.txt"
LOCK_DEPS = REPO_ROOT / "scripts" / "lock_deps.sh"

#: Every `name==version` pinned exactly in pyproject's dev extra. These are the
#: ones a range would break, so these are the ones worth cross-checking.
_EXACT_PIN = re.compile(r'"([A-Za-z0-9_.-]+)==([^"]+)"')


def _pyproject_exact_pins() -> dict[str, str]:
    return {
        name.lower().replace("_", "-"): version
        for name, version in _EXACT_PIN.findall(PYPROJECT.read_text(encoding="utf-8"))
    }


def _locked_versions() -> dict[str, str]:
    locked: dict[str, str] = {}
    for line in REQUIREMENTS_DEV.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or "==" not in line:
            continue
        name, _, version = line.partition("==")
        locked[name.strip().lower().replace("_", "-")] = version.strip()
    return locked


def test_every_exact_pin_matches_the_compiled_lockfile() -> None:
    """A pin that pyproject states exactly and the lockfile states differently
    means the audited file describes an environment nobody installs."""
    pinned = _pyproject_exact_pins()
    locked = _locked_versions()
    disagreements = {
        name: (version, locked[name])
        for name, version in pinned.items()
        if name in locked and locked[name] != version
    }

    assert not disagreements, (
        "pyproject pins these exactly and requirements-dev.txt disagrees "
        f"(pyproject, lockfile): {disagreements}. Regenerate with the command "
        "in the lockfile's header."
    )


def test_the_regeneration_script_uses_the_command_that_made_the_file() -> None:
    """The file records its own generator in line 2. A script that runs a
    different one guarantees the next regeneration reshapes the file."""
    header = REQUIREMENTS_DEV.read_text(encoding="utf-8").splitlines()[1]
    tool = header.split("#", 1)[1].strip().split()[0]
    script = LOCK_DEPS.read_text(encoding="utf-8")

    assert f"{tool} pip compile" in script or f"{tool} " in script, (
        f"requirements-dev.txt says it was generated by {tool!r}, but "
        f"scripts/lock_deps.sh does not use it"
    )


def test_the_retired_production_lockfile_is_not_regenerated() -> None:
    """DG-281. `requirements.txt` was retired to `_not_used/` because nothing
    read it and it had drifted 113 lines from pyproject.

    A script that still writes it would recreate the file on the next run, and
    an unread artefact that keeps coming back is the state it was retired from.
    """
    assert not (REPO_ROOT / "requirements.txt").exists(), (
        "requirements.txt is back at the repo root; it was retired to "
        "_not_used/requirements/ and nothing reads it"
    )
    assert "-o requirements.txt" not in LOCK_DEPS.read_text(encoding="utf-8"), (
        "scripts/lock_deps.sh still compiles the retired production lockfile"
    )


def test_the_retired_copy_says_why_it_was_retired() -> None:
    """`CLAUDE.md`: retired things move to `_not_used/` *with a note saying why
    and what replaced them*. A file parked without one is indistinguishable
    from one somebody forgot."""
    note = REPO_ROOT / "_not_used" / "requirements" / "RETIRED.md"

    assert note.is_file(), "the retired lockfile has no RETIRED.md beside it"
    assert "uv.lock" in note.read_text(encoding="utf-8"), (
        "the note has to name what replaced it, not only that it is gone"
    )
