# mypy: ignore-errors
"""DG-271. The compiled dev lockfile has to agree with what compiled it.

Two ways it had drifted:

`pyproject.toml` pins `ruff==0.16.4` exactly, and it explains at length why the
formatter cannot take a range — 0.15.22 and 0.16.4 disagree about blank lines
before a class, which turned `develop` red and dragged two unrelated PRs down
with it (DG-270). `requirements-dev.txt` still pinned 0.15.20: the exact
version DG-270 was written to stop anyone resolving.

`scripts/lock_deps.sh` regenerates it with `pip-compile`, while the file's own
header records `uv pip compile`. Two generators for one artefact is the shape
DG-280 had, and it ends the same way — whoever regenerates decides what lands.

`pip-audit --strict` reads this file in CI, so a stale pin is not cosmetic: the
audit is answering about versions nobody installs.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = REPO_ROOT / "pyproject.toml"
REQUIREMENTS_DEV = REPO_ROOT / "requirements-dev.txt"
LOCK_DEPS = REPO_ROOT / "scripts" / "lock_deps.sh"

#: Every `name==version` pinned exactly in pyproject's dev extra. These are the
#: ones a range would break, so these are the ones worth cross-checking.
_EXACT_PIN = re.compile(r'"([A-Za-z0-9_.-]+)==([^"]+)"')


def _pyproject_exact_pins() -> dict[str, str]:
    return {
        name.lower().replace("_", "-"): version
        for name, version in _EXACT_PIN.findall(PYPROJECT.read_text(encoding="utf-8"))
    }


def _locked_versions() -> dict[str, str]:
    locked: dict[str, str] = {}
    for line in REQUIREMENTS_DEV.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or "==" not in line:
            continue
        name, _, version = line.partition("==")
        locked[name.strip().lower().replace("_", "-")] = version.strip()
    return locked


def test_every_exact_pin_matches_the_compiled_lockfile() -> None:
    """A pin that pyproject states exactly and the lockfile states differently
    means the audited file describes an environment nobody installs."""
    pinned = _pyproject_exact_pins()
    locked = _locked_versions()
    disagreements = {
        name: (version, locked[name])
        for name, version in pinned.items()
        if name in locked and locked[name] != version
    }

    assert not disagreements, (
        "pyproject pins these exactly and requirements-dev.txt disagrees "
        f"(pyproject, lockfile): {disagreements}. Regenerate with the command "
        "in the lockfile's header."
    )


def test_the_regeneration_script_uses_the_command_that_made_the_file() -> None:
    """The file records its own generator in line 2. A script that runs a
    different one guarantees the next regeneration reshapes the file."""
    header = REQUIREMENTS_DEV.read_text(encoding="utf-8").splitlines()[1]
    tool = header.split("#", 1)[1].strip().split()[0]
    script = LOCK_DEPS.read_text(encoding="utf-8")

    assert f"{tool} pip compile" in script or f"{tool} " in script, (
        f"requirements-dev.txt says it was generated by {tool!r}, but "
        f"scripts/lock_deps.sh does not use it"
    )


def test_the_retired_production_lockfile_is_not_regenerated() -> None:
    """DG-281. `requirements.txt` was retired to `_not_used/` because nothing
    read it and it had drifted 113 lines from pyproject.

    A script that still writes it would recreate the file on the next run, and
    an unread artefact that keeps coming back is the state it was retired from.
    """
    assert not (REPO_ROOT / "requirements.txt").exists(), (
        "requirements.txt is back at the repo root; it was retired to "
        "_not_used/requirements/ and nothing reads it"
    )
    assert "-o requirements.txt" not in LOCK_DEPS.read_text(encoding="utf-8"), (
        "scripts/lock_deps.sh still compiles the retired production lockfile"
    )


def test_no_retired_file_still_looks_like_a_manifest() -> None:
    """DG-290. GitHub's dependency graph parses manifests by filename, anywhere
    in the repository, and raises alerts from what it finds.

    Retiring `requirements.txt` into `_not_used/` did not take it out of range:
    three aiohttp alerts followed the file to its new path, for a version
    nothing here installs. `.github/dependabot.yml` cannot help — its
    `exclude-paths` suppresses automatic pull requests, not alerts, and the
    dependency graph offers no path exclusion. A name it does not recognise is
    the only lever.

    The cost of the noise was concrete: a real alert, `cryptography` in
    `uv.lock` (DG-289), sat in a list of four where three were about software
    the project does not run.
    """
    tracked = subprocess.run(
        ["git", "ls-files"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()

    # Matched the way the dependency graph matches, not the way a tidy naming
    # convention would: it picks up `dev-requirements.txt` and
    # `archive-requirements.txt` as readily as `requirements.txt`. A guard
    # narrower than the scanner it guards against is a guard that passes while
    # the alerts arrive.
    manifests = [
        path
        for path in tracked
        if Path(path).name in {"pyproject.toml", "uv.lock", "Pipfile", "Pipfile.lock"}
        or ("requirements" in Path(path).name and Path(path).suffix == ".txt")
    ]
    live = {"pyproject.toml", "uv.lock", "requirements-dev.txt"}
    strays = [path for path in manifests if path not in live]

    assert not strays, (
        "these tracked files carry a live manifest's name but are not one of "
        f"the project's real manifests, so the dependency graph will raise "
        f"alerts from them: {strays}"
    )


def test_the_retired_copy_says_why_it_was_retired() -> None:
    """`CLAUDE.md`: retired things move to `_not_used/` *with a note saying why
    and what replaced them*. A thing parked without one is indistinguishable
    from one somebody forgot.

    Since DG-291 the directory is no longer tracked, so the committed record is
    the root `RETIRED.md` index. This asserts against that: the per-directory
    notes still exist in a working checkout, but a fresh clone does not have
    them and the record has to survive a fresh clone.
    """
    index = REPO_ROOT / "RETIRED.md"

    assert index.is_file(), "there is no retirement index at the repository root"
    body = index.read_text(encoding="utf-8")
    assert "requirements" in body, "the index does not mention the retired lockfile"
    assert "uv.lock" in body, (
        "the index has to name what replaced it, not only that it is gone"
    )


WORKFLOW = REPO_ROOT / ".github" / "workflows" / "test.yml"


def test_ci_audits_what_actually_ships() -> None:
    """DG-289. The audited file and the installed file were different files.

    `pip-audit --strict` read `requirements-dev.txt` and reported clean, while
    the Dockerfile installed from `uv.lock` — which pinned `cryptography 49.0.0`,
    inside a high-severity advisory. `requirements-dev.txt` held 50.0.0. A green
    audit was answering about an environment nobody ships, and the comment above
    the step claimed the opposite in as many words.

    Asserted against the workflow rather than by running an audit here: this has
    to hold with no network and on a machine that has never resolved the lock.
    """
    workflow = WORKFLOW.read_text(encoding="utf-8")

    assert "uv export" in workflow, (
        "CI does not export uv.lock, so nothing audits the versions a user "
        "actually installs"
    )

    exported = workflow.split("uv export", 1)[1]
    assert "pip-audit" in exported, (
        "uv.lock is exported but never handed to pip-audit — exporting it and "
        "not auditing it is worse than not exporting it, because the step name "
        "says the audit happened"
    )
